server:
  port: 8082
spring:
  application:
    name: "loanapplication-service"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
  r2dbc:
    host: "localhost"
    port: "3306"
    username: "root"
    password: "raizDiego"
    database: "loanapplication-db"
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"

logging:
  level:
    root: INFO
    co.com.pragma: TRACE

routes:
  paths:
    loans: "/api/v1/solicitud"

